#.
#Recipe Toggles
#These options control whether Creator Sword's Create processing recipes are loaded.
#
#Changes to these options require re-entering the world or restarting the server
#before recipe visibility and availability are refreshed.
#
[recipes]
	#.
	#.
	#Enable Create mixing recipes for Ominous Essence fluids.
	enableOminousEssenceRecipes = true
	#.
	#Enable Create recipes for crafting Trial Keys.
	enableTrialKeyRecipes = true
	#.
	#Enable Create recipes for crafting Ominous Trial Keys.
	enableOminousTrialKeyRecipes = true
	#.
	#Enable Create recipes for crafting Precision Trial Keys.
	enablePrecisionTrialKeyRecipes = true
	#.
	#Enable Create recipes for crafting Precision Ominous Trial Keys.
	enablePrecisionOminousTrialKeyRecipes = true
