#.
#Allowed Values: CELSIUS, FAHRENHEIT, KELVIN
temperatureUnit = "CELSIUS"
#.
#Allowed Values: PASCAL, BAR, ATMOSPHERE, PSI, MM_OF_MERCURY, INCH_OF_MERCURY
pressureUnit = "PASCAL"
#.
#Whether rocket thrusters on contraptions should always produce particles shown during countdown.
alwaysEnableThrusterParticles = false
#.
#The visibility of other planets in the sky
#Always: Always visible, matching vanilla star visibility.
#Outside Atmosphere: When above the planet's atmosphere defined in the server config or on planets where stars are always visible.
#Never: never render additional stars, fully empty sky.
#Allowed Values: ALWAYS, OUTSIDE_ATMOSPHERE, NEVER
planetVisibility = "ALWAYS"
#.
#The visibility of additional stars in the sky
#Always: Always visible, matching vanilla star visibility.
#Outside Atmosphere: When above the planet's atmosphere defined in the server config or on planets where stars are always visible.
#Never: never render additional stars, fully empty sky.
#Allowed Values: ALWAYS, OUTSIDE_ATMOSPHERE, NEVER
starVisibility = "OUTSIDE_ATMOSPHERE"

#.
[debug]
	#.
	debugSealerBounds = false
